### ISSUE TITLE
Wrong "ADDRESS" opcode handling

### ISSUE THREAD

**Issue by p0n1** [b-mueller/laser-ethereum#14]
Confusing code here:

https://github.com/b-mueller/laser-ethereum/blob/55b7c50c45f926af055a1410d516aaf947a8db25/laser/ethereum/svm.py#L617-L618

I think the "ADDRESS" execution should return the address of current contract as follows.

```python
state.stack.append(environment.address)
```

**Comment by b-mueller** [comment]
That's correct, thanks!

**Comment by b-mueller** [comment]
Btw, not sure if you're interested, but we're looking for someone to do further work on laser-ethereum - implementing the remaining opcodes etc. Ping me on the Mythril Gitter if you like.
