### ISSUE TITLE
Confusing 'SLOAD' op handling

### ISSUE THREAD

**Issue by p0n1** [b-mueller/laser-ethereum#16]
https://github.com/b-mueller/laser-ethereum/blob/55b7c50c45f926af055a1410d516aaf947a8db25/laser/ethereum/svm.py#L771-L786

Why should we try to access the storage of `environment.sender`/`caller` first when calling 'SLOAD' op.

**Comment by b-mueller** [comment]
Thanks for the feedback @p0n1 and sorry for the late reply, I had notifications turned off for this repo. 

You're right, that doesn't make any sense. It should be ` gblState.environment.active_account`. Thanks for pointing this out!
