### ISSUE TITLE
laser.ethereum.svm's BitVec calls cause child process crash on the Arch linux-hardened kernel

### ISSUE THREAD

**Issue by 10a7** [b-mueller/laser-ethereum#2]
Here's a strange one. I've been tracing an issue where `compile_solidity` in Mythril will fail with `Popen` causing ENOMEM and then the child process getting killed with a segfault. I am on Arch Linux with Python 3.6.3 and Z3 4.5.0, using the [linux-hardened](https://www.archlinux.org/packages/?name=linux-hardened) kernel [hardening patchset from Copperhead](https://github.com/copperhead/linux-hardened).

The problem is that when the `BitVec` constructor is used in L74-78 of `laser/ethereum/svm.py`, all `Popen` (or other subprocess calls, such as `os.system`) will fail. `strace` shows the child process as hitting `ENOMEM` and then being killed with `SIGSEGV`, although there is plenty of memory available on the system. If the `BitVec` references in L74-78 are commented out, the subprocess will run successfully.

A reduced test case is available here:
```
import laser.ethereum.svm
import subprocess

p = subprocess.Popen(['echo', 'foo'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print(p.communicate())
print(p.returncode)
```

Running this with the hardened patchset will cause the subprocess to return `-11` as the return code. Running a normal configuration Arch Linux kernel will allow the subprocess to successfully complete.

I'm not sure who to file a bug against or where, but this is as far as I've traced down the rabbit hole. I'm not expecting a fix as I'm running a non-standard kernel configuration, but it may be worthwhile to log this issue in the documentation for Mythril or laser-ethereum for others scratching their head with this one.

**Comment by b-mueller** [comment]
Hi @10a7, sorry for the late reply, I almost never visit this repo...

That's indeed very weird behavior! Since you traced it to the `BitVec` constructor, I suspect that it is somehow cause by the native Z3 libraries. Maybe some kind of limit to the number of open pipes is enforced by the hardened kernel (just guessing here)?

Also not sure what to do with this issue. Did you find a workaround?

**Comment by 10a7** [comment]
I’m not sure what do to with the issue either. The workaround was to use the non-hardened kernel. 😒 I didn’t trace it any further than this but I wanted to have somewhere on the record that the problem occurs, as it’s not evident what is going on when you run Mythril. Perhaps just add a line to the documentation for now?

**Comment by b-mueller** [comment]
I'll leave this as an open issue for now. Might be worth also creating an issue in the [Z3Prover repo](https://github.com/Z3Prover/z3/).

**Comment by 10a7** [comment]
I haven't been able to come up with a simplified testcase for Z3 yet. IIRC `BitVec()` worked fine in a Python file on its own on the hardened kernel. If I have the time I'll look into this further.
