### ISSUE TITLE
No matching distribution found for laser-ethereum>=0.17.5 (from mythril)

### ISSUE THREAD

**Issue by ksloven** [b-mueller/laser-ethereum#21]
Hi,

I just tried to pip install mythril (the new version as I already had it before and it was working fine on my machine).
But now, based on the changes you made 4 hours ago from laser-ethereum >= 0.17.4 to laser-ethereum >= 0.17.5 (in Mythril), it seems 17.5 isn't found.

Collecting laser-ethereum>=0.17.5 (from mythril)
  Could not find a version that satisfies the requirement laser-ethereum>=0.17.5 (from mythril) (from versions: 0.5.4, 0.5.6, 0.5.9, 0.5.11, 0.5.14, 0.5.15, 0.5.20, 0.17.1, 0.17.2)
No matching distribution found for laser-ethereum>=0.17.5 (from mythril)

**Comment by birdofpreyru** [comment]
0.17.5 is in PyPI: https://pypi.org/project/laser-ethereum/
