### ISSUE TITLE
Possible incorrect parameter passed to _sym_exec call

### ISSUE THREAD

**Issue by suhabe** [b-mueller/laser-ethereum#30]
Was `new_glbState` on 1147 supposed to be passed to the `_sym_exec` call in the subsequent line? Otherwise `new_glbState` isn't used anywhere.

 https://github.com/b-mueller/laser-ethereum/blob/2ae38155c8dd6ff95692718157ea51a079ef6926/laser/ethereum/svm.py#L1147-L1148

**Comment by b-mueller** [comment]
That's correct, fixed in 7a864f748a878679280d093c450409e89cca607e.
