### ISSUE TITLE
NameError: name 'BitVec' is not defined

### ISSUE THREAD

**Issue by arun-munagala** [b-mueller/laser-ethereum#33]
I probably did something wrong. 
But i followed the instructions in setup.py
and when i run the command "myth --init-db"
i get the follwing error: 
File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 41, in Account
    def __init__(self, address, code=None, contract_name="unknown", balance=BitVec("balance", 256)):
NameError: name 'BitVec' is not defined

**Comment by arun-munagala** [comment]
Updated modules and now everything works fine.

**Comment by ghost** [comment]
I have a same problem,could u tell me which modules u updated?

**Comment by norhh** [comment]
@qingchenldl , can you uninstall the previous versions and then do `pip install mythril==0.20.0`
