### ISSUE TITLE
Ethereum bytecode execution

### ISSUE THREAD

**Issue by arun-munagala** [b-mueller/laser-ethereum#40]
from laser.ethereum import svm
from mythril.ether.soliditycontract import SolidityContract
contract = SolidityContract("solidity_examples/underflow.sol", "Under")

disassembly = contract.disassembly
--------------
How can i pass just bytecode? for the above example how can i passi it in the variable contract?

**Comment by JoranHonig** [comment]
Hi @arun-munagala ,
You can use a ETHContract to do this:

```
from mythril.ether.ethcontract import ETHContract
contract = ETHContract(your_byte_code)
```

**Comment by JoranHonig** [comment]
Btw, for quick questions you can always hop by on gitter: https://gitter.im/ConsenSys/mythril

**Comment by arun-munagala** [comment]
@JoranHonig Thank you so much!
